apiVersion: apps/v1
kind: Deployment
metadata:
  name: formation-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: formation-service
  template:
    metadata:
      labels:
        app: formation-service
    spec:
      containers:
        - name: formation-service
          image: rimzoghlami/cicd-pipeline-formation-service:latest
          ports:
            - containerPort: 9094
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql:3306/Formation-Service?createDatabaseIfNotExist=true"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              value: ""
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: "http://eureka-server:8761/eureka"
---
apiVersion: v1
kind: Service
metadata:
  name: formation-service
spec:
  selector:
    app: formation-service
  ports:
    - port: 9094
      targetPort: 9094
  type: ClusterIP
