apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
        tier: backend
    spec:
      containers:
        - name: user-service
          image: rimzoghlami/cicd-pipeline-user-service:latest
          ports:
            - containerPort: 8089
              name: http-port
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "kubernetes"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql:3306/onsjabbes?createDatabaseIfNotExist=true"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              value: ""
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: "http://eureka-server:8761/eureka"
            - name: EUREKA_INSTANCE_HOSTNAME
              value: "user-service"
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"
            - name: SERVER_SERVLET_CONTEXT_PATH
              value: "/tests"
            - name: SPRING_MAIL_HOST
              value: "smtp.gmail.com"
            - name: SPRING_MAIL_PORT
              value: "587"
            - name: SPRING_MAIL_USERNAME
              value: "hajerhr7@gmail.com"
            - name: SPRING_MAIL_PASSWORD
              value: "apec nvum joqt ymlc"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /tests/actuator/health
              port: 8089
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /tests/actuator/health
              port: 8089
            initialDelaySeconds: 120
            periodSeconds: 30
            timeoutSeconds: 10
      initContainers:
        - name: wait-for-mysql
          image: busybox:1.35
          command: ['sh', '-c', 'until nc -z mysql 3306; do echo waiting for mysql; sleep 5; done;']
        - name: wait-for-eureka
          image: busybox:1.35
          command: ['sh', '-c', 'until nc -z eureka-server 8761; do echo waiting for eureka; sleep 10; done;']
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    app: user-service
    tier: backend
spec:
  selector:
    app: user-service
  ports:
    - port: 8089
      targetPort: 8089
      name: http-port
  type: ClusterIP
